# Performance Measures

## In class exploration and discussion

### Exercise

Consider two generic prediction models $f_1$ and $f_2$ for univariate, continuous outcome $Y \in \mathbb{R}$ with multivariate predictors $X \in \mathbb{R}^d$. Without knowing anything about how the prediction models were created, describe how you might evaluate the performance of $f_1$ and $f_2$ if you know the true relationship between $X$ and $Y$. Try to be precise in your description, using mathematical notation if helpful.

### Exercise

Read [RMS 5.1.2](https://hbiostat.org/rmsc/validate#sec-val-index). Describe/define/develop an example of the following terms

1. Discrimination (rank based and variation based)
2. Calibration
3. Calibration curve

### Exercise

1. Sketch a calibration curve that represents poor discrimination but good calibration
2. Sketch a calibration curve that represents good discrimination but poor calibration

### Exercise

```r
# may need to be installed first pak::pak("thomasgstewart/ds6021b")
require(ds6021b)
```

Consider the three predictor setting: $X \in \mathbb{R}^3$. Let

$$X_1, X_2 \sim N(0,1)\qquad X_3\sim \text{BIN}(n=1, p=0.4)$$

$$Y\sim N(\mu({\mathbf X}),1)\qquad \mu({\mathbf X}) = \sqrt{5}\,\text{sigmoid}(X^2_1 + X_3) + \sqrt{5}\,\text{sigmoid}(X_2)\,X_3$$

1. Simulate data from the model.
2. Create the calibration curves for $f_1$ to $f_5$, which are in the `ds6021b` package.
3. Calculate a global measure of model performance.
4. Add a loess curve to the calibration curve as a measure of local performance.

## Student exploration

1. Select one of the papers from the list below
2. For the initial exploration, do the following:
   - Prepare a summary of the key ideas. Be prepared to describe/illustrate the concepts in a concrete example.
   - Review the instructions for the student presentation and come with an idea/sketch of the simulation you'll perform.
3. For the student presentation, do one of the following and come prepared to present it to the class:
   - Replicate a simulation or example from the paper
   - Develop your own simulation study which explores a concept discussed in the paper
   - Complete the simulation study described below.

### Paper list

| Paper | Title |
|-------|-------|
| [Efron 1986](https://www.jstor.org/stable/2289236) | How Biased is the Apparent Error Rate of a Prediction Rule? |
| [Efron 1983](https://sites.stat.washington.edu/courses/stat527/s14/readings/Efron_jasa1983.pdf) | Estimating the Error Rate of a Prediction Rule: Improvement on Cross-Validation |
| [Efron 1997](https://www.jstor.org/stable/2965703) | Improvements on Cross-Validation: The .632+ Bootstrap Method |
| [Steyerberg et al. (2001)](https://www.sciencedirect.com/science/article/pii/S0895435601003419) | Internal validation of predictive models: efficiency of some procedures for logistic regression analysis |
| [Varma & Simon (2006)](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-7-91) | Bias in error estimation when using cross-validation for model selection |
| [Bates, Hastie & Tibshirani (2023)](https://www.tandfonline.com/doi/full/10.1080/01621459.2023.2197686) | Cross-Validation: What Does It Estimate and How Well Does It Do It? |

### Simulation study (Efron and Tibshirani 1997)

The goal of Efron and Tibshirani 1997 was to persuade readers to use the 0.632+ bootstrap estimate of the error rate rather than alternatives. To demonstrate its superiority, the authors began with a simple simulation study involving a binary outcome $(Y_i)$ and two predictors $(\mathbf{T}_i = (T_{i1}, T_{i2}))$. The simulation study was to demonstrate that the variance of the estimator (and consequently the mean squared error) of the estimator was lower.

First, you will replicate the results presented in the paper.

**Data generation model**

$$Y_i \sim \text{BIN}(1, 0.5)$$

$$\mathbf{T}_i|Y_i=y_i \sim N_2\left(\left[\begin{array}{c} y_i-1/2 \\ 0\end{array}\right], I_2\right)$$

where $I$ is the identity matrix and $N_2$ is the bivariate normal distribution.

**Methods evaluated**

The paper only evaluated methods 1 and 2, but we list several more for the curious student.

1. Leave-one-out cross-validation (LOO CV)
2. 0.632+ bootstrap
3. 10-fold cross-validation
4. 0.632 bootstrap
5. Bootstrap
6. Naive

**Models evaluated**

The paper considers models 1 and 2, but an extension might consider more:

1. LDA
2. 1-NN
3. Regression with polynomial surface (linear or logistic)
4. Random forest
5. Neural net

**Simulation parameters**

1. N = 10, 20, 30, 40, 50, 75, 100

**Plan**

1. Before beginning the simulation, consider how you will display the results. Devise a figure that will succinctly show the results and support the goal of the paper.
2. Consider modular programming
3. Start with a single simulation setting (method/model/N).