project:
  type: book

book:
  title: "DS6400 Portfolio"
  author: "Stephen Olsen"
  date: ""
  chapters:
    - index.qmd
    - 01_Performance_Measures.qmd
    - 01_Performance_Measures_2.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



