project:
  type: book

book:
  title: "DS6400 Portfolio"
  author: "Stephen Olsen"
  date: ""
  chapters:
    - index.qmd
    - part: "01: Performance Measures"
      chapters:
        - 01_Performance_Measures_Notes.qmd
        - 01_Performance_Measures_1.qmd
        - 01_Performance_Measures_2.qmd
    - part: "02: Visualizing the Model"
      chapters:
        - "02_Visualizing_the_Model_Notes.qmd"
        - "02_Visualizing_the_Model_1.qmd"
    - part: "03: 4 models"
      chapters:
        - "03_Model_Notes.qmd"
        #- "03_Generalized_Linear_Model.qmd"
        - "03_Neural_Net.qmd"
        #- "03_Random_Forest.qmd"
        #- "03_Ordinal_Regression.qmd"
        - "03_Comparison.qmd"

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



